### ISSUE TITLE
binding using annotations only

### ISSUE THREAD

**Issue by ShahOdin** [codingwell/scala-guice#106]
> If you find a feature we don't support but want, implement it and send us a pull request. Alternatively, you can file an issue and we may or may not get to it.

In the Play framework, I believe I can bind things without an explicit `Module`. is that something we can do using this library? or is the module created internally by Play somewhere? I'd appreciate a minimal example.

**Comment by tsuckow** [comment]
That has to be something from the guicesupport class from play framework


https://www.playframework.com/modules/guice-1.0/home
