### ISSUE TITLE
How one can use assisted injection with scala-guice? Is it supported ?

### ISSUE THREAD

**Issue by Maatary** [codingwell/scala-guice#20]
Hi, 

I have been using google-guice with the assisted inject mechanism for a while. As i am in scala, and just discover scala-guice, i'm interested in using it as well. However i'm confused as to how to use assisted injection with it. There is not example of using assisted inject with it. Especially, would it support assisted-inject library ?

Hence my question here is: is it possible to use assisted injection with scala-guice, if yes, please could provide a simple example ? or at least indicated the library needed. 

For google guice i use, javax.inject.jar, guice-3.0.jar, guice-assistedInject.jar

**Comment by sebigavril** [comment]
Where do you import `typeLiteral` from? Or is it a function written by you?

**Comment by sebigavril** [comment]
Think I've found it: `import net.codingwell.scalaguice.typeLiteral`
