### ISSUE TITLE
Bind Instances with annotation

### ISSUE THREAD

**Issue by beeva-pablojimenez** [codingwell/scala-guice#44]
I'm trying to do something like this;

Binding:
bind[A].annotatedWith( Names.named("name") ).toInstance["B"]

Getting from injector:
val b = injector.instance[A]

There is a compilation error if i try get from injector with ( Names.named("name") ) 
type mismatch; found : com.google.inject.name.Named required: Manifest[A]

Thanks

**Comment by tsuckow** [comment]
So you get a compiler error with:
```
val b = injector.instance[A]( Names.named("name") ) 
```

**Comment by nbauernfeind** [comment]
How does this usage differ from the test?

https://github.com/codingwell/scala-guice/blob/master/src/test/scala/net/codingwell/scalaguice/InjectorExtensionsSpec.scala#L50

**Comment by beeva-pablojimenez** [comment]
tsuckow, i have an error compiller with the code you are write ( found : com.google.inject.name.Named required: Manifest[A])

nbauernfeind, the diferent between your test and my code is that i,m binidng instances, not classes

In the other hand, i'm using scala-guice_2.10 with version <version>3.0.2</version> because using <version>4.0.0-beta5</version> i have maven problem: No versions available for com.google.code.findbugs:jsr305:jar:[1.3, 1.4) within specified range

**Comment by beeva-pablojimenez** [comment]
Hi all, the problems is solved on 4.0.0-beta5 version. I have instaled com.google.code.findbugs:jsr305:jar:[1.3, 1.4) in my maven local repository and everything is working now.

Thank you for your help

**Comment by nbauernfeind** [comment]
@tsuckow Can we remove the need for findbugs? I always forget to add it as an exclusion. I don't know if it's only a maven build issue or if other build systems have trouble with that dependency requirement... but it's non-obvious for new users.

**Comment by tsuckow** [comment]
Not sure why it needs to be separately installed. I also don't remember the last time I checked it's output. I probably mostly used it with Jenkins. I think it definitely should be made to "just work" or be removed

**Comment by tsuckow** [comment]
So, I don't understand the issue with jsr305. That package is needed for using Guava with Scala. It is listed as a compile time dependency in build.sbt It should "just work" and does for me.

**Comment by beeva-pablojimenez** [comment]
I'm using maven. I have seen guice's pom file and it needs jsr305 as dependence. When i run maven install, it told me: "No versions available for com.google.code.findbugs:jsr305:jar:[1.3, 1.4) ", I don't understand why maven show that error.

**Comment by tsuckow** [comment]
Oh.. So I have it listed as a compile dependency, should we be pulling it in for users of the library as well? Thoughts @nbauernfeind ?

**Comment by nbauernfeind** [comment]
Guava has findbugs listed as an optional dependency. That can be seen here: https://github.com/google/guava/blob/8f1df29aa3babf441c262aedb6176714c6749596/guava/pom.xml#L21

If it's possible to mark it as optional in SBT, that might be best?

For some reason SBT must be turning this dependency into the "provided" scope instead of "compile" scope (for maven users). If scala-guice uses it at all, then I would try and mark it optional. If it's required, then fix the requirement to a specific version (latest preferably). If it's not used, I would just omit it in case it ever disappears from guava.
