### ISSUE TITLE
Cut a release for Guice 4.0.0 final

### ISSUE THREAD

**Issue by mushtaq** [codingwell/scala-guice#45]

**Comment by tsuckow** [comment]
I can't believe they finally did it. I should look at this Monday as I am out of town.

**Comment by tsuckow** [comment]
I've updated the snapshot version 4.0.0-SNAPSHOT. Give that a spin and if the wheels don't fall off let me know and I'll promote it to 4.0.0

**Comment by mushtaq** [comment]
I tried using snapshot but sbt could not resolve it. Do I have to add a new
resolver?

Thanks.

**Comment by tsuckow** [comment]
Well this is embarrassing. All this time I thought I was pushing SNAPSHOT releases I had a typo.

It should "just work" now. But if not it is at https://oss.sonatype.org/content/repositories/snapshots/

Or even more specifically [oss.sonatype.org/.../scala-guice_2.11/4.0.0-SNAPSHOT/](https://oss.sonatype.org/content/repositories/snapshots/net/codingwell/scala-guice_2.11/4.0.0-SNAPSHOT/)

**Comment by mushtaq** [comment]
Ok, after I added resolvers += Resolver.sonatypeRepo("snapshots"), all my
tests pass on local box. But I can not push it to CI as snapshots repo are
not accessible from CI. So all green from side.

Thanks.

**Comment by tsuckow** [comment]
Oh..  So I have it listed as a compile dependency, should we be pulling it in for users of the library as well? Thoughts Nate?

**Comment by nlochschmidt** [comment]
Just tested the 4.0.0-SNAPSHOT in our project and everything works as expected. And as a bonus the Guava evicted messages (#40) will finally be fixed \o/.

**Comment by tsuckow** [comment]
Good to hear!

I am trying to get #44 squared away. I am swamped, I hope to make a new snapshot tonight changing the related dependency and then hopefully get the full release out before the long weekend.

**Comment by nbauernfeind** [comment]
I was almost done with #42 well back in the day. Does it make sense to finish that off? An almost complete implementation is here: https://github.com/nbauernfeind/scala-guice/tree/TypeTag.

However, I think we would need to drop support for scala 2.10 since TypeTag's are not thread safe (see: http://docs.scala-lang.org/overviews/reflection/thread-safety.html). 2.11 has been release for only about a year (since 4/16/2014).

Or, if not dropping support, we could branch off of 2.10 but some changes would not be portable. Maybe we could have one last 2.10 release to celebrate Guice's 4.0?

**Comment by tsuckow** [comment]
I am thinking we could keep support for 4.0.0 and then drop support and do
a 4.0.1. If too much protest we keep a branch for 2.10 after that.

**Comment by tsuckow** [comment]
Alright. I have pushed a new SNAPSHOT that fixes #44. Please give it a spin and make sure that simple change hasn't broke the world. If no one protests I plan to release 4.0.0 Friday before I leave on holiday. Then we should see about merging #42 for 4.0.1

**Comment by tsuckow** [comment]
Should be synced to maven central shortly

**Comment by mushtaq** [comment]
Cool, thanks.
