### ISSUE TITLE
scala-guice does not bind primitive types correctly

### ISSUE THREAD

**Issue by ShengC** [codingwell/scala-guice#48]
class IntProvider extends Provider[Int] {
  def get() = 1
}

trait Foo[T] { def get(): T }

class FooProvider extends Provider[Foo[Long]] {
  def get() = new Foo[Long] { def get() = 1L }
}

IntProvider is bound as java.lang.Object, and FooProvider is bound as Foo[java.lang.Object]. If instead I bind to the java primitives directly, types are right.

**Comment by nbauernfeind** [comment]
Can you please include your guice module?

**Comment by ShengC** [comment]
Sorry, this seems to be a very old issue without followup. This really is sporadic, and I cannot reproduce it any more.

**Comment by nbauernfeind** [comment]
Ok. Thanks for the update. Feel free to close this issue.
