### ISSUE TITLE
Binding wildcard types doesn't use correct type literal

### ISSUE THREAD

**Issue by Vrolijkx** [codingwell/scala-guice#70]
I have problems with binding wildcard types in scala Guice. If you define a binding like ```bind[Container[_]].toInstance(someInstance)``` or ```bind[Containter[_ <: SomeImpl].toInstance(someInstance)``` then injections of these types into constructors/fields will fail. 
I have pinpointed the problem to the way scalaGuice generates a typeLiteral see spec below:

```
val typeLiteralScalaGuice = typeLiteral[Container[_ <: Impl1]]
val typeLiteralJavaWay = new TypeLiteral[Container[_ <: Impl1]] {}

typeLiteralJavaWay shouldEqual typeLiteralScalaGuice //this failes
```

**Comment by tsuckow** [comment]
Should be fixed in 4.2.1
Sorry about the delay
