### ISSUE TITLE
getInstance() with constructor parametrs

### ISSUE THREAD

**Issue by Koyirov** [codingwell/scala-guice#73]
Hello,
I'm using guise version 4.1.0 in my project, but I'm  not right with getInstance () function. injector.getInstance (classOf [startgame]), where startgame has to take a parameter. But if I do parameter purely, I take a error "starting game does not take a parameter." Can someone explain that to me? Thanks in advance.

**Comment by tsuckow** [comment]
You may want to look at https://github.com/google/guice/wiki/FrequentlyAskedQuestions#how-do-i-pass-a-parameter-when-creating-an-object-via-guice

You may also try asking https://groups.google.com/forum/#!forum/google-guice
Be sure to include details of your bindings and not just getInstance
