### ISSUE TITLE
Replace uses of Manifest with ClassTag / TypeTag

### ISSUE THREAD

**Issue by ashleymercer** [codingwell/scala-guice#79]
If a type is owned by an `object` then it looks like [binding is special-cased](https://github.com/codingwell/scala-guice/blob/develop/src/main/scala/net/codingwell/scalaguice/TypeConversions.scala#L85) so, for example, the following works as expected:

```scala
object Foo {
  case class Bar(value: Int)
}

bind[Foo.Bar].toInstance(Foo.Bar(value = 1))
```

However, if the type `Bar` is instead used as a type parameter for some generic type, then the binding fails with `ScalaReflectException` because the enclosing type cannot be found in the `Mirror`, so this:

```scala
trait Factory[T] {
  def get(): T
}

class FactoryImpl[T] @Inject()(value: T) extends Factory[T] {
  def get(): T = value
}

bind[Factory[Foo.Bar]].to[FactoryImpl[Foo.Bar]]
```

results in

```
scala.ScalaReflectionException: class Foo in JavaMirror with DependencyClassLoader{...elided...}
	at scala.reflect.internal.Mirrors$RootsBase.staticClass(Mirrors.scala:129)
	at scala.reflect.internal.Mirrors$RootsBase.staticClass(Mirrors.scala:29)
	at net.codingwell.scalaguice.TypeConversions$.findOwnerOf(TypeConversions.scala:87)
	at net.codingwell.scalaguice.TypeConversions$.scalaTypeToJavaType(TypeConversions.scala:66)
	at net.codingwell.scalaguice.TypeConversions$.$anonfun$scalaTypeToJavaType$1(TypeConversions.scala:67)
	...
```

**Comment by nbauernfeind** [comment]
What versions of scala and scala-guice are you using?

**Comment by ashleymercer** [comment]
Ahh, knew I'd forget something! As follows:

**Scala:** 2.12.8
**Java:** 1.8.0_202
**scala-guice:** 4.2.3

**Comment by ashleymercer** [comment]
I reproduced a minimal test case in a clean project and it works just fine. The only difference when I see the error is that I'm running Play in DEV mode: this is a well-known source of ClassLoader-related gotchas since Play does a lot of tricks to enable hot compile/reload during development.

The weird thing is that pretty much all the rest of scala-guice works as expected (certainly, I use it to bind a bunch of other types, and reflection finds them just fine) so I'll keep digging and see if this is something that can be fixed on the scala-guice side.

**Comment by ashleymercer** [comment]
Think I've found it: some of the methods in scala-guice use `Manifest` which is part of the older (pre-2.10) reflection API. Looks like this doesn't play nicely with Play's dev-mode ClassLoader shenanigans since I can see from debugging that it ends up with the wrong `ClassLoader` instance (it only has access to external dependencies, and _not_ the project classes).

Since scala-guice no longer supports older versions of Scala I'm going to submit a PR which updates all the method signatures to use `ClassTag` or `TypeTag` (as appropriate) and these end up with the right `ClassLoader`.

For anyone else who hits this bug in the meantime, it looks like `BindingExtensions.toType` already has the correct signature, and is functionally equivalent to `ScalaLinkedBindingBuilder.to` so you can just rewrite the above example as:

```scala
import net.codingwell.scalaguice.BindingExtensions._

// This works, even in Play DEV mode!
bind[Factory[Foo.Bar]].toType[FactoryImpl[Foo.Bar]]
```
