### ISSUE TITLE
Add provider to InjectorExtensions

### ISSUE THREAD

**Issue by GalLalouche** [codingwell/scala-guice#90]
Guice's `Injector` has a [`Provider<T> getProvider(Class<T> type)`](https://google.github.io/guice/api-docs/latest/javadoc/com/google/inject/Injector.html#getProvider-java.lang.Class-) method. It would be nice if `InjectorExtensions` would have a `provider[T: Manifest]: Provider[T]` method, similar to its `instance[T: Manifest]: T` methods.

**Comment by tsuckow** [comment]
#91 is in 4.2.10
