### ISSUE TITLE
New guice has been released

### ISSUE THREAD

**Issue by heikkijuntunen** [codingwell/scala-guice#94]
There is new Guice available. Is there plans to support that one?

https://github.com/google/guice/wiki/Guice501

**Comment by tsuckow** [comment]
You about gave me a heart attack when I saw the year 2020 in the release notes. Thought I was gonna relive the year again.

If I get a chance I'll see about trying to update this weekend.

**Comment by tsuckow** [comment]
`5.0.0` should be synced to maven central shortly targeting `Guice-5.0.1`
