### ISSUE TITLE
bind[X[Nothing]] fails when trying to instatiate Nothing. 

### ISSUE THREAD

**Issue by borissmidt** [codingwell/scala-guice#95]
It tries to instantiate `Exception in thread "main" java.lang.ClassNotFoundException: scala.Nothing` 
https://stackoverflow.com/questions/54369014/cant-bindsttpbackendtry-nothing

**Comment by tsuckow** [comment]
I'll see if I can't add handing of Nothing later this week.

**Comment by cacoco** [comment]
@tsuckow I took a go at fixing this.

**Comment by tsuckow** [comment]
scala-guice 5.0.1 should sync to maven central shortly. Many thanks to @cacoco for making the pull request so I just had to validate the changes.

**Comment by borissmidt** [comment]
Thank you for fixing it so fast!
